### PR TITLE
support ROA export in JSON format

### PR DESCRIPTION
**Pull request by reschke**
- designed to make it compatible with Octo and Routinator
- note: currently lacks trust anchor information (which does not appear to be available at time of generation anymore)
- JSON output by string operations, should be safe given the datatypes present

### CODE REVIEW

**Comment by pcarana** [comment]
Thanks for this PR! I'll adequate a couple of things in the next days.

One of them is to add an argument to set the output format, something like `--output.format` (allowed values: 'csv' or 'json'), and according to its value, print the output to whatever is set at `--output.roa`.

Regarding the TA information related to each ROA, let me see if I can do something efficient (I wouldn't like to hold a string on each record of the DB).

**Comment by reschke** [comment]
Yes.

As you can see, I chose the most simplistic approach. I appreciate if you can do it more elegantly.

**Comment by reschke** [comment]
@pcarana - thanks for reviewing and improving this!

**Comment by pcarana** [comment]
Great! Thanks for doing the merge, that was the next step. Sorry that this hasn't been moving faster, but right now I'm doing this on my free time.

**Pull request merged**
