### PR TITLE
Main

### PR DESCRIPTION
**Pull request by THEWWWTHING**

### CODE REVIEW

**Review by Irsservices — APPROVED** [review]

**Comment by ydahhrk** [comment]
Wait... I just noticed we have two AS identifiers (`ASID.h` and `ASId.h`), and they're basically identical.

Is this giving you trouble in a case-sensitive file system? If so, it would seem to me the proper solution would be to delete one of them, not make them fully identical.

**Comment by ydahhrk** [comment]
Ok, I suppose you're not going to elaborate further at this point, so I fixed what I thought was broken, okay. Hopefully it'll solve whatever problem you're having.

**Comment by Irsservices** [comment]
Can you explain briefly so I can understand better on how to go about this.

+19453457018

**Comment by ydahhrk** [comment]
As proposed, THEWWWTHING's patch turned the `ASId.h` module into an [exact clone](https://github.com/NICMx/FORT-validator/blob/26e9760834d7f9b609200d5b9fb9b269d2a97c2d/src/asn1/asn1c/ASId.h) of the [`ASID.h`](https://github.com/NICMx/FORT-validator/blob/26e9760834d7f9b609200d5b9fb9b269d2a97c2d/src/asn1/asn1c/ASID.h) module.

Whatever the goal was, the patch was misguided because none of the `ASId` usages was updated, so the code did not compile.

While reviewing the patch, I realized there was no reason to keep `ASId` and `ASID` separate. They were the same type, only spelled a little differently. My theory is that THEWWWTHING downloaded the code into a filesystem which, because of file name collision, wasn't capable of containing both files (`ASId.h` and `ASID.h`) in the same folder. So one thing lead to another and they ended up uploading a pull request in which both files had the same content.

I fixed the pull request by merging the two types. The issue is now closed because I already merged the code to `main`.

You can download the latest version of the code by clicking `<> Code` > `Download ZIP` [here](https://github.com/NICMx/FORT-validator).

**Pull request closed without merging**
